/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js projects and kept here so TypeScript can
// understand Next-specific types before the first local build.
